### ISSUE TITLE
Delete spaces after/before key name in module/instance properties

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#1]
if a set a module property with following value : {{ prop_instance}}/prop_instance, It adds 2 instance properties (one with a space before key name, one without)
--> Hesperides should not create 2 different properties

Other case : using a global property at module level with a space should work

LINK TO [hesperides#1](https://github.com/voyages-sncf-technologies/hesperides/issues/1)

**Comment by stidiovip** [comment]
We should also take care of already existing global property with "spaces"

**Comment by stidiovip** [comment]
Fixed on release 2.0.0
