### ISSUE TITLE
Unreachable nested buttons (cross browser compatibility)

### ISSUE THREAD

**Issue by zessirb** [voyages-sncf-technologies/hesperides-gui#101]
There are nested buttons inside shared/list-of-items.html ; using firefox, the inner button (used to delete a techno) cannot be reached. Also, this is not considered valid HTML.

**Comment by thomaslhostis** [comment]
@zessirb Aurais-tu un screenshot ?

**Comment by Lucas-C** [comment]
Je clôture au profit de https://github.com/voyages-sncf-technologies/hesperides-gui/issues/124
