### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#107]
Hi !

is it possible to add the link to https://voyages-sncf-technologies.github.io/hesperides-gui/ in Help menu ?
(and possibly put url in config.json in casethe url changes)

**Comment by Lucas-C** [comment]
RAF: Il reste à relire la PR #115 de Victor

**Comment by Lucas-C** [comment]
@thomaslhostis : si tu as pu tester, cette issue doit pouvoir être fermée :)
