### ISSUE TITLE
local change lost with platform containing dash

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#109]
1/ I have a platform called "FOO-XXX" (important : with dash)
2/ I save locally changes
3/ I click on "local changes pending"
--> I lose all changes

**Comment by Lucas-C** [comment]
Nous venons de tester et on ne peut pas reproduire ce bug, tout semble fonctionner.
Peux-tu vérifier stp @nboury-vsct ?

**Comment by Lucas-C** [comment]
Je clôture
