### ISSUE TITLE
Can error properties without error

### ISSUE THREAD

**Issue by bubulemaster** [voyages-sncf-technologies/hesperides-gui#110]
For example, if I display global properties but, my web brower can't get properties (this call never response http://localhost:8080/rest/applications/KTN/platforms/USN1/properties?path=%23 because Hesperides is down or network cut).

I can add a properties and send it.

When we push data, we set platform_id, but platform_id is get before get data.

That mean is work and errase data.

**Comment by Lucas-C** [comment]
Cannot reproduce, closing
