### ISSUE TITLE
Diff properties for module in only one level logical group doesn't works

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides-gui#111]
If I have a module into only one logical group (or I think more than 2 logicals groups), diff properties on this module display diff panel, but doesn't works.

Correct code here https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/src/app/properties/properties.js#L1451 to doesn't get name and other values with absolute index in array path, but with a relative index, as used here : https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/src/app/application/application.js#L59

Make path function and values generic in factory, as https://github.com/voyages-sncf-technologies/hesperides-gui/tree/master/src/app/local_changes

**Comment by Lucas-C** [comment]
@mareths @JordanKergoat : bug résolu ?

**Comment by Lucas-C** [comment]
Vu avec Jordan, c'est corrigé.
