### ISSUE TITLE
Commentary annotation doesn't seem to work correctly

### ISSUE THREAD

**Issue by JefffLD** [voyages-sncf-technologies/hesperides-gui#125]
Hello, 
When I use the @comment annotation it doesn't display it into my module. 
Actually, in my template, those syntax doen't work : 
- "my_prop={{my_prop|@comment "description"}} 
- "my_prop={{my_prop|"description"}}
- "my_prop={{my_prop|description}}
- "my_prop={{ my_prop|description }}
- "my_prop={{my_prop | description}}
- "my_prop={{ my_prop | description }}
- "my_prop={{my_prop|@comment "description" @default 60000}} works well but I have got only mu default value (like "my_prop={{my_prop|@comment "description" @default "60000"}})... 

I think it doesn't work well... 
Thank you, 
Regards

**Comment by JefffLD** [comment]
It seems that the commentary appears after the value has been deleted (if there were a value beore the update).

**Comment by Lucas-C** [comment]
Merci @JefffLD de nous avoir remonté ce bug !
Je l'ai déplacé dans le backlog du backend : https://github.com/voyages-sncf-technologies/hesperides/issues/379
