### ISSUE TITLE
(little) Mistake on the English translation

### ISSUE THREAD

**Issue by JefffLD** [voyages-sncf-technologies/hesperides-gui#126]
Hello, 

When you try to use @required annotations with @default annotation we have an error message : 
"propertie 'xxx' canno't be @require et @default !" instead of 
"Propertie 'xxx' cannot be @required et @default!". 

Thnak you, 
Regards, 
JF.

**Comment by bubulemaster** [comment]
Lol, do you see franch work "et" ?

**Comment by Lucas-C** [comment]
This has been resolved
