### ISSUE TITLE
Amélioration de l'affichage valorisation properties 

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#135]
Demande de Serge Galica :

Bonjour,
Certaines erreurs d’insertion pourraient être évités si on pouvait apercevoir l’ensemble de la chaine à l’écran.
Serait-il possible de modifier l’affichage en élargissant le champ dynamiquement pour mieux controler svp ?

**Comment by Lucas-C** [comment]
Screenshot fourni par Serge :
![image-2018-10-30-15-50-45-858](https://user-images.githubusercontent.com/925560/55790421-99ab4280-5abc-11e9-9819-1af3394d3a4c.png)

**Comment by Lucas-C** [comment]
Vu avec lui : plus précisément le souhait est d'avoir un affichage multilignes pour les valeurs très longues

> quand tu dois ajouter des infos dans la valeur du champ, sur une ligne de champ importante, la mis à jour peut provoquer des problemes de controle visuel, et du coup fausser la mis à jour
> du coup le comportement serait de pouvoir aggrandir la zone en hauteur pour un affichage complet de la valeur du champ
> c'est spécifique aux champs qui sont d'une longueur impossible actuellement à afficher en totalité
