### ISSUE TITLE
Diff : origin_timestamp n'est pas fourni par le front lors de la récupération des propriétés

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#136]
![microsoftteams-image](https://user-images.githubusercontent.com/4296630/45821129-bfbbf180-bce8-11e8-9907-fe65e6b475d8.png)

**Comment by Lucas-C** [comment]
Corrigé par https://github.com/voyages-sncf-technologies/hesperides-gui/pull/272
