### ISSUE TITLE
 Wrong error message "Saving is not possible. At least one property does not respect..."

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#137]
Reported by @JordanKergoat on 20 Apr 2017 :

> When trying to edit a production platform without having production acces right. The displayed message is not the one expected. Instead you get :
> 
> "Saving is not possible. At least one property does not respect @required and/or @pattern annotations"
> 
> The correct message would be :
> 
> "Updating a production platform is reserved to production role"

**Comment by Lucas-C** [comment]
ID du msg : https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/src/app/i18n/label_en.json#L54

**Comment by christiangraves** [comment]
I would like to correct this issue

**Comment by Lucas-C** [comment]
Great !

Note that because this error occurs [when trying to update properties by maling a POST request on the API](https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/src/app/application/application.js#L404), the error message **label** should be **generic** : it can happen for several reasons, including the "production role" & "value not matching @pattern" situations

So in order to resolve this issue, we should either :
- display the REST API backend detailed error message (best solution IMHO), so that the end user could pinpoint exactly what is the exact issue
- add some JS logic in order to detect the real issue (is it due to annotations or production role ?)

**Comment by Lucas-C** [comment]
The message is now:

>  Setting properties of a production platform is reserved to production role
