### ISSUE TITLE
Bouton de copie de groupe logique

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#153]
Demande issue du sondage 2017

**Comment by Lucas-C** [comment]
Suggestions:
- rajouter un bouton "copier" au niveau de chaque groupe logique
- en cliquant dessus, une modale s'ouvre pour permettre à l'utilisateur de spécifier un autre groupe logique
- lorsque l'utilisateur valide, tous les modules déployés dans le groupe logique **source** sont copiés dans le groupe logique **destination**

**Comment by thomaslhostis** [comment]
On ne copie pas les propriétés et on verra en fonction des retours

**Comment by Lucas-C** [comment]
2 tests à prévoir :
- vérifier que lorsque un module est copié dans un groupe existant, contenant d'autres modules, le nouveau est bien ajouté et les pré-existants ne sont pas supprimés
- vérifier que lorsqu'un module est copié dans un groupe en contenant déjà un de même nom + version + releaseType, rien ne change
- vérifier que lorsqu'un module est copié dans un groupe en contenant déjà un de même nom, mais avec une version ou un releaseType différent, une popin de confirmation est affichée à l'utilisateur

**Comment by Lucas-C** [comment]
@Bhoye05 Pourras-tu stp en profiter pour déplacer le `newFeature.label` depuis `src/app/properties/add_box.html:36` dans cette nouvelle modale ?

**Comment by Bhoye05** [comment]
OK
