### ISSUE TITLE
Create an option to display only the required properties in the module properties list

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#158]
Demande de @JordanKergoat

Il devrait être assez simple de rajouter une checkbox, mais peut-on facilement savoir, en JS, quelles propriétés sont `@required` ?

**Comment by Lucas-C** [comment]
La réponse à ma question est oui :)

L'idée est de rajouter un bouton/filtre "show only required properties" à ce niveau :
![2019-10-07 11_44_03-Hesperides _ Properties](https://user-images.githubusercontent.com/925560/66301706-ed75d780-e8f7-11e9-8c00-f1c01482d861.png)

**Comment by thomaslhostis** [comment]
### [Hacktoberfest] Create an option to display only the required properties in the module properties list

**Comment by Lucas-C** [comment]
@Bhoye05 : je me permets de rouvrir cette _issue_ pour ne pas oublier de rajouter un test BDD, comme je le suggérais ici : https://github.com/voyages-sncf-technologies/hesperides-gui/pull/322#pullrequestreview-299281297

Ton code est nickel, mais comme un bouton est rajouté je pense qu'un test de non régression serait bien utile :)
