### ISSUE TITLE
Les valorisations de propriétés ne respectant pas le pattern ne sont pas sauvegardé dans le ngModel AngularJS, sans qu'aucun message n'en informe l'utilisateur

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#175]
La valeur renseigné est donc perdue dès l'utilisateur navigue ailleurs.

Pour identifier ce cas en console JS:
```javascript
var propName = ... // si un point est présent, il faut l'échapper doublement: \\.
angular.element($('#simple-properties-list_value-property-isnotglobale-input-'+propName)).data().$ngModelController.$valid
```

**Comment by thomaslhostis** [comment]
Test e2e à compléter : `should not save properties for a wrong pattern (TREE MODE)`

**Comment by Lucas-C** [comment]
Idéalement on devrait afficher les contrôles "de surface" des input à l'utilisateur (via API `form.$errors` AngularJS)
