### ISSUE TITLE
Retirer le bouton de suppression de plateforme

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#195]
Les ops sont effrayés par ce bouton. Il y a déjà eu une boulette de faite et la restauration n'étant pas fonctionnelle, ils ont dû refaire la plateforme à la main. Je propose de le retirer et de ne laisser cette fonctionnalité que dans l'API.

**Comment by thomaslhostis** [comment]
Cela annulerait cette demande : https://github.com/voyages-sncf-technologies/hesperides-gui/issues/190

**Comment by Lucas-C** [comment]
Nous avons convenu de le désactiver temporairement, et de le rétablir lorsque les ACLs auront été implémentés
