### ISSUE TITLE
Lorsqu'on crée une copie de plateforme non taggée prod vers une plateforme taggée prod, les mdp deviennent des étoiles au déploiement

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#204]
Bug rapporté par Nicolas Hubby, potentiellement lié à https://github.com/voyages-sncf-technologies/hesperides-gui/issues/203 et/ou au back. À reproduire.

**Comment by Lucas-C** [comment]
Non reproduit : aucune étoile n'apparait, que ce soit dans la liste des propriétés ou dans la prévisualisation du fichier d'instance

**Comment by Lucas-C** [comment]
J'ai essayé de reproduire le problème avec l'utilisateur qui nous la remonté initialement, sans succès. Je clôs ce ticket pour le moment
