### ISSUE TITLE
Required properties doesn't work fine on the front

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides-gui#21]
Front the hesperides gui, the required property can't be saved when they're empty.
But when to fill in the required property save it and then clean it and save egain, the empty value is saved.

**Comment by JordanKergoat** [comment]
I still can save empty required properties

**Comment by JordanKergoat** [comment]
I still can save empty required properties

**Comment by thomaslhostis** [comment]
Fixed
