### ISSUE TITLE
Le #switch_hide-show-instance des settings n'est pas pris en compte

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#239]
> en vue arbre avant sur XYZ j'avais ABC -> CDE-> FGH par exemple. Maintenant j'ai l'inverse et tout est déroulé par défaut.

**Comment by Lucas-C** [comment]
Note: il existe des tests concernant ce bouton dans l''un des 2 derniers fichiers de spec non encore restaurés: https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/test/e2e/protractor-conf.js#L32

**Comment by thomaslhostis** [comment]
L'ordre des groupes logiques et des modules est corrigé pour le mode arbre et le mode bloc dans cette pull request : https://github.com/voyages-sncf-technologies/hesperides-gui/pull/250
