### ISSUE TITLE
Showing a merge dialog rather than failing to save to the backend

### ISSUE THREAD

**Issue by lenaing** [voyages-sncf-technologies/hesperides-gui#24]
For now, it seems that when we save uncommitted changes to the backend while the same properties have been modified by another user or in another session, the commit to the backend fails with a concise error popup.

An enhancement would be to compare the properties the user wants to save with the actual data in the backend and show a "merge dialog" enabling the user to review and select properties he/she would like to replace. This merge dialog could look like the current diff dialog.

The resulting selection might be applied with a PATCH commit, like described in this issue : #11, thus avoiding to resend all the modifications.

**Comment by JordanKergoat** [comment]
This is solved along with #39 #40 #43
