### ISSUE TITLE
Faciliter le debug des tests end-to-end (e2e) dans Travis CI

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#279]
Nous avons récemment eu des difficultés à déboguer nos tests e2e, avec plusieurs situations où les tests passaient sur nos postes de développement mais pas dans la pipeline Travis CI.

Deux suggestions pour améliorer cette situation :
- afficher systématiquement les logs du navigateur dans le log Travis - _cf._ https://github.com/voyages-sncf-technologies/hesperides-gui/issues/98
- capturer une screenshot en cas d'échec d'un test, et le publier sur le net (ex: sur Imgur avec [imgur-uploader](https://pypi.org/project/imgur-uploader/))

**Comment by thomaslhostis** [comment]
L'exécution des tests sur Travis est désormais stabilisée donc ce besoin n'est plus d'actualité.
