### ISSUE TITLE
Transformer les tests E2E en tests BDD

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#280]
Objectifs:
- utiliser l'API pour initialiser les données des tests _end to end_, et ainsi éviter les préconditions implicites dues à l'ordre d'exécution des tests (_cf._ [protractor-conf.js](https://github.com/voyages-sncf-technologies/hesperides-gui/blob/2019-09-25/test/e2e/protractor-conf.js#L25)) et faciliter l'exécution d'un seul test ciblé
- mieux structurer nos tests en employant des scénarios Gherkins, avec une meilleure réutilisation des _steps_ de la glue

**Comment by Lucas-C** [comment]
Lié à https://github.com/voyages-sncf-technologies/hesperides-gui/issues/279

**Comment by Lucas-C** [comment]
J'ai initialisé un 1er test BDD dans https://github.com/voyages-sncf-technologies/hesperides-gui/commit/1ec7172

À partir de maintenant, le plan est de migrer les anciens tests existants au nouveau format, et de ne plus ajouter de tests dans le format `jasmine` avec `describe() & `it()`.

Un point à vérifier : que les hooks `After` de _cleanup_ s'exécutent bien en cas d'échec d'un test

**Comment by thomaslhostis** [comment]
En cours. RAF :
- [ ] menu
- [ ] technos
- [ ] modules
- [ ] platforms
- [ ] logic-representation
- [ ] diff
- [ ] preview-files
- [ ] role_production
- [ ] properties
- [ ] settings
