### ISSUE TITLE
Réintroduire les commentaires et la possibilité de faire des diffs dans l'historique des événements

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#283]
Fonctionnalité présente avant la refonte, disparue depuis. Potentiellement un problème d'output dans le backend. Il faut retrouver ce qui était affiché (modification de modules, templates, propriétés, etc.) et le remettre comme tel, ou l'améliorer.

**Comment by thomaslhostis** [comment]
De plus, des tests end-to-end désactivés vérifient la présence de commentaires dans l'historique des événements

**Comment by Lucas-C** [comment]
En lien : https://github.com/voyages-sncf-technologies/hesperides/issues/303 (Historiques des évenements Modules/Technos)

**Comment by Lucas-C** [comment]
Discuté avec @thomaslhostis : on ne comprend pas comment le legacy récupérait l'historique des événements des propriétés de modules déployés ! En effet l'appel à l'API ne précisait pas de `propertiesPath`.

Il va donc falloir ajouter une nouvelle ressource et dissocier:
- les `events` des modules
- les `events` des modules déployés et les changements de propriétés associés

**Comment by Bhoye05** [comment]
**Besoins**

- [ ] Visualisation des modifications des valorisations de 

- [ ] propriétés

Visualisation des changements de versions de modules déployés
Visualisation des ajouts/suppressions de modules déployés
Visualisation des modifications de versions de platformes
Visualisation des ajouts/suppressions de templates (dans un module ou une techno)
Comparer les valorisations d'un module entre 2 versions

**Comment by thomaslhostis** [comment]
Développement en cours :
* Benjamin va créer un component
* Mamadou suit le sujet
* Je m'occupe des tests BDD

**Comment by Lucas-C** [comment]
La partie _backend_ est prête ( _cf._ https://github.com/voyages-sncf-technologies/hesperides/pull/830 & https://github.com/voyages-sncf-technologies/hesperides/issues/826 ), reste à traiter le _frontend_
