### ISSUE TITLE
Le mode Edition de template ne prend plus le plein écran (F11)

### ISSUE THREAD

**Issue by rbihore** [voyages-sncf-technologies/hesperides-gui#294]
La possibilité de faire F11 sur l'écran d’édition d'un template et ainsi de voir le template en plei écran ne fonctionne plus (depuis quand ? je ne sais pas).

C'était assez pratique pour lire et modifier des templates qui font plusieurs lignes / plusieurs colonnes.

Aujourd'hui, l'appui sur la touche F11 met toute la fenêtre du navigateur en plein écran, la fenêtre du template restant à sa taille au milieu de l'écran.

**Comment by Lucas-C** [comment]
Cette régression date de mai dernier : https://github.com/voyages-sncf-technologies/hesperides-gui/commit/8d43429#diff-f8f5681966c2a89650ad0bb647737af5

Je jette un oeil
