### ISSUE TITLE
calendar in diff modal is not viewable depending on screen resolution

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#30]
for example with 1440x900 landscape you cannot see hours of calendar element : Is it possible to display the calendar more in the middle ?

**Comment by mareths** [comment]
"Min:" is not centered, as "Hour:" on top

**Comment by mareths** [comment]
https://github.com/stidiovip/hesperides-datetime-picker/pull/1

Need update bower repo for hesperides-datetime-picker v0.1.24 before pull request changes on hesperides-gui

**Comment by stidiovip** [comment]
@mareths, this has been merged.

**Comment by JordanKergoat** [comment]
This issue has been fixed, the calendar is move to the center of the screen for screen that could not display correctly the whole calendar
