### ISSUE TITLE
Les tooltips au hover sur les inputs de la page des propriétés sont décalés

### ISSUE THREAD

**Issue by Lucas-C** [voyages-sncf-technologies/hesperides-gui#303]
![2019-09-18 16_18_16-Hesperides _ Properties](https://user-images.githubusercontent.com/925560/65156787-f75e9600-da2f-11e9-8551-239bbbee1e80.png)
![2019-09-18 16_16_17-Hesperides _ Properties](https://user-images.githubusercontent.com/925560/65156789-f75e9600-da2f-11e9-8947-3dd3627bfb86.png)

**Comment by Lucas-C** [comment]
@thomaslhostis je ne sais pas si ça vaut même le coup de les conserver...

**Comment by thomaslhostis** [comment]
@Lucas-C De conserver les tooltips dans le formulaire de valorisation ?

**Comment by Lucas-C** [comment]
Oui

**Comment by thomaslhostis** [comment]
Je propose de supprimer le tooltip de la clé parce qu'il ne fait que répéter le nom de la propriété et de passer le tooltip potentiel de la valeur (en cas d'utilisation d'annotation) sur la clé : 
![image](https://user-images.githubusercontent.com/4296630/65433085-a3332780-de1c-11e9-8c83-bed081623bf8.png)
