### ISSUE TITLE
Bloc mode performance issue

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#31]
When you have huge application with a large amount of module and mostly a huge number of instances, the loading time is significantly increased in bloc mode display.

As a first solution, it could be implemented a display/hide button over modules instances. By default, instances will be hidden. But they could be displayed at any time on demand using the display/hide button.

**Comment by mareths** [comment]
https://github.com/voyages-sncf-technologies/hesperides-gui/pull/33

**Comment by JordanKergoat** [comment]
An eye icon is now present next to the "+" icon (used to add an instance). This new icon allows to display/hide instances
