### ISSUE TITLE
Permettre la suppression des propriétés inutilisées au niveau plateforme

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#316]
La demande consiste à permettre la suppression des propriétés valorisées qui ne correspondent pas à des propriétés déclarées dans les templates.

Le problème vient du fait que cela pollue notamment le résultat du diff de propriétés.

**Comment by Lucas-C** [comment]
Ce n'est pas déjà ce que fait ce bouton ?
![2019-09-27 19_52_43-Hesperides _ Properties](https://user-images.githubusercontent.com/925560/65790662-6d65aa00-e160-11e9-863d-8a0a586ca3a7.png)

**Comment by Lucas-C** [comment]
Vu avec O. Blondeau : oui c'est bien ça, mais ça serait bien pratique au niveau plateforme.

**Comment by thomaslhostis** [comment]
Proposition de porter cette fonctionnalité dans le backend : https://github.com/voyages-sncf-technologies/hesperides/issues/803

**Comment by Lucas-C** [comment]
Note: penser à mettre à jour la doc utilisateur une fois ceci implémenté :)
