### ISSUE TITLE
Modifier le switch de sélection des globales dans la liste des propriétés

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#327]
Ajouter un switch pour les cacher

**Comment by JordanKergoat** [comment]
L'idée est de rendre la cohérence de l'interface qu'elle a perdu, à savoir :  
- Les switch ne permettent pas de faire apparaitre des propriétés, elles sont déjà présente de base, ils jouent juste le role de filtres
- Il faut donc que le filtre de globales actuel soit inversé, par défaut toutes les propriétés sont listée, et en l'activant on ne retrouve plus que les globales
- Il faut ajouter un switch qui permet de masquer les globales

Pourquoi cet ajout de switch ? Il faut savoir qu'historiquement ce switch de globale pas pratique à été ajouté pour permettre au plateformes utilisants énormément de globale de pouvoir les cacher pour facilité a lecture des propriété "locale du module".

A titre d'exemple certaines plateformes avaient par exemple 5 propriété local de module vs 250 propriété globale. Il était donc compliqué pour les utilisateurs de trouver les locales

La remise en cohérence des switchs de filtres leur supprimerai cette possibilité, il faut donc ajouter un switch d'un nouveau type, un switch de masquage.

Le comportement par défaut devrai toujours être d'afficher toutes les propriétés du modèle, et pouvoir en filtrer/masquer, mais devoir activé un switch pour en afficher certaine est tout simplement une horreur à mon sens, voila :)

**Comment by Lucas-C** [comment]
Merci pour l'explication et le contexte historique !
C'est super utile, et je comprends mieux ta pertinente suggestion :)

Donc on parle bien uniquement des variables globales de même nom qu'une propriété de module ?
