### ISSUE TITLE
Ne pas griser le bouton de sauvegarde de propriétés lorsqu'une propriétés obligatoire n'est pas renseignée

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#334]
L'idéal est de laisser l'utilisateur cliquer sur le bouton et de lui afficher un message d'erreur global ("propriété 1 et propriété 2 sont obligatoires, veuillez saisir une valeur"), puis de mettre en focus et en surbrillance les propriétés concernées.

La vérification doit se faire dans un premier temps côté front mais à la validation du formulaire. Si l'utilisateur ne peut pas cliquer sur le bouton de sauvegarde, il ne saura pas nécessairement pourquoi.

**Comment by Lucas-C** [comment]
Normalement le champ concerné est entouré d'un bandeau rouge.

On pourrait également indiquer un message plus explicite dans la zone entre le bouton et la liste des propriétés.

Pourquoi "La vérification doit se faire à la validation du formulaire" ?
