### ISSUE TITLE
Download all module files by a given version

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides-gui#34]
As a Hesperides user
I Want to download all modules files by a given version
To treat them outside Hesperides

Modules files are only template files, with no valuation of the properties

**Comment by mareths** [comment]
Pull request https://github.com/voyages-sncf-technologies/hesperides-gui/pull/41

**Comment by JordanKergoat** [comment]
From the module screen, you download either all your file at once, or each of them separately
