### ISSUE TITLE
Remplacer les icônes WARNING par des icônes distinctes dédiées 

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#344]
Dans la liste des propriétés, remplacer les icônes WARNING par des icônes distinctes dédiées identifiant s'il s'agit de propriétés globales ou s'il s'agit de la valorisation par défaut.

Ajouter une section légende.

Lié à https://github.com/voyages-sncf-technologies/hesperides-gui/issues/146

**Comment by thomaslhostis** [comment]
Il faudrait identifier les différents cas qui nécessitent d'afficher un tooltip dans la liste des propriétés de module et attribuer une icône spécifique à chaque cas.

**Comment by Bhoye05** [comment]
**vérifier s'il s'agit: **
- des propriétés globales
- champ password
- valeur par default

**Comment by thomaslhostis** [comment]
Vu ensemble : mentionner la convention de pictos dans la doc utilisateur
