### ISSUE TITLE
@pattern et @required ne sont pas vérifiés lorsqu'ils sont en première position de la liste

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#353]
La sauvegarde d'une propriété qui ne respecte pas l'annotation @pattern ou @required est possible lorsque la propriété se trouve en première position (par ordre alphabétique) de la liste des propriétés à valoriser. Cela se produit sur Chrome mais pas Firefox.

**Comment by Lucas-C** [comment]
Reproduit par @Bhoye05 sur Firefox

**Comment by Lucas-C** [comment]
Nous n'avons pas réussi à reproduire d'éventuel bug sur le `md-virtual-repeat` de manière isolé avec @Bhoye05 : https://codepen.io/Lucas-C/pen/MWYBwpX

Nous allons continuer à investiguer

**Comment by Lucas-C** [comment]
Nous avons découvert que la méthode [FormController.$addControl](https://github.com/angular/angular.js/blob/master/src/ng/directive/form.js#L150) d'AngularJS n'était pas appelé pour le 1er élément de la liste dans le cas de reproduction du bug.
Il nous parait difficile d'aller plus loin dans l'identification de l'origine du bug, mais un appel manuel à `FormController.$addControl` devrait nous fournir une solution de comportement du bug satisfaisante, car succinte et très localisée.
