### ISSUE TITLE
No Consistency between auto-complete fields

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides-gui#37]
Auto-complete list have not the same behavior between techno/module/application search field.

In Application search field, an application list appears when I click on the input fields, that I type a text or not.
While on techno or module search field, I should type almost 3 letters to display the autocomplete list.

**Comment by thomaslhostis** [comment]
Hello @mareths,
Penses-tu que c'est toujours pertinent étant donné le nombre de modules et des technos ?

**Comment by mareths** [comment]
C'était plus une question de cohérence avec les 2 autres types de recherche.
Ca peut aussi être perturbant pour ceux qui n'utilisent pas souvent l'appli / ceux qui ne connaissent pas exactement la syntaxe du module qu'ils cherchent (déjà eu la remarque à l'époque par certains devs)

**Comment by Lucas-C** [comment]
Ok, merci

**Comment by thomaslhostis** [comment]
Ce sera amélioré via #151
