### ISSUE TITLE
Informer que la valeur par défaut d'une propriété est la même que celle surchargée.

### ISSUE THREAD

**Issue by Bhoye05** [voyages-sncf-technologies/hesperides-gui#380]
Demande de Nicolas P. :
> je viens soumettre une petite demande d'évolution
avec l'icone qui a été ajoutée récemment il me semble, permettant de consulter la valeur par défaut, serait-il possible de mettre en avant que cette valeur par défaut est la même que celle surchargée.
> une icône dédiée "valeur par défaut == valeur surchargée" aurait un intérêt

**Comment by thomaslhostis** [comment]
Lié à https://github.com/voyages-sncf-technologies/hesperides-gui/issues/387
