### ISSUE TITLE
GET /applications/APP/platforms provoque une NullPointerException

### ISSUE THREAD

**Issue by Bhoye05** [voyages-sncf-technologies/hesperides-gui#385]
curl 'http://localhost/rest/applications/APP/platforms' -X PUT -H 'Content-Type: application/json;charset=UTF-8' -d '{"platform_name":"DEV","application_name":"APP","application_version":"1.0","production":false,"modules":[{"id":0,"path":"#logic#group","instances":[]}],"version_id":32}'

**Comment by Lucas-C** [comment]
Non reproduit avec la dernière version, je clôture :
```
$ curl -sku $USER:$PASSWORD "https://$HES_HOSTNAME/rest/applications/APP/platforms"
Request method 'GET' not supported
```
