### ISSUE TITLE
L'icône "i" de tooltip des propriétés est obsolète

### ISSUE THREAD

**Issue by thomaslhostis** [voyages-sncf-technologies/hesperides-gui#388]
Depuis qu'il y a des icônes spécifiques aux types de propriétés (password, default, etc.) accompagnés de leur tooltip, plus besoin de l'icône générique "i" ni son son tooltip.

**Comment by Bhoye05** [comment]
Traité en même temps que issue #380  Fix #391

**Comment by Lucas-C** [comment]
Il semble qu'il reste toujours un tooltip ici:
```
src/app/properties/simple-properties-list.html:110
<i class="fa fa-info-circle e2e-property-tooltip" ng-if="key_value_property.valuedByInstance"><md-tooltip md-direction="left">{{key_value_property.tooltip}}</md-tooltip></i>
```

**Comment by thomaslhostis** [comment]
Bien vu

https://github.com/voyages-sncf-technologies/hesperides-gui/pull/413

**Comment by thomaslhostis** [comment]
En fait on a toujours besoin de ce tooltip pour le cas où la propriété est valorisée dans une instance. On a même un même : https://github.com/voyages-sncf-technologies/hesperides-gui/blob/master/test/bdd/features/platforms/module-properties-list.feature#L83

**Comment by Lucas-C** [comment]
Ok donc je clôture
