### ISSUE TITLE
Updating Instance name

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#42]
Updating instance name won't work if you already did something at the instance level, saving properties or renaming instance.

Eg 1 : Refresh page -> update instance name -> WORK
Eg 2 : Refresh page -> change instance valorisation -> Save -> update instance name -> FAIL

**Comment by JordanKergoat** [comment]
I will use this issue to have some update a the instance part, such as, adding the missing comment part while saving

**Comment by JordanKergoat** [comment]
Actually, I noticed that when an instance is saved, it doesn't note update the instance ref used in the GUI. Which cause wrong synchronisation between displayed value against real values.  
The displayed value being the value you actually want to save, and the real values being the actual value to save.
This cause loss of data because you save values that you already saved and you lose your expected value without noticing it.

**Comment by stidiovip** [comment]
Fixed on release CHAOS_2.2.1
