### ISSUE TITLE
Allow users to provide feedback

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#47]
it would be useful to allow users to provide feedback through mail or other way

**Comment by mareths** [comment]
Integration of angular-bootstrap-feedback project

**Comment by mareths** [comment]
Next try with angular-feedback project:
https://github.com/jacobscarter/angular-feedback/tree/master
http://jacobscarter.github.io/angular-feedback/#/

**Comment by JordanKergoat** [comment]
When trying to report a feedback i noticed that when the comment contains special characters it simply fail while a sentance with "regular" character work as expected

**Comment by nboury-vsct** [comment]
@mareths fixed this !
