### ISSUE TITLE
Blinking display for application with multiple instance

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides-gui#49]
Have a lot of instances in an application, named with 12 characters, and the instances are displayed in several line.
If the latest instances are near the right border of the box, and when the mouse is over it, the instance go to the start of the next line to display eyes and delete button, with some blink.

**Comment by mareths** [comment]
http://codepen.io/mareths/pen/GNPmar

**Comment by thomaslhostis** [comment]
@mareths Merci pour ce retour. Je n'arrive pas à reproduire ce bug. Peux-tu nous donner un exemple d'application sur laquelle ça se produit ?

**Comment by thomaslhostis** [comment]
Vu avec @mareths 

Effectivement, lorsqu'on affiche beaucoup d'instances en mode block, il y a un clignotement lié à l'affichage des boutons de prévisualisation et de suppression d'instance.

**Comment by thomaslhostis** [comment]
RIP mode bloc

**Comment by mareths** [comment]
C’est moche, vous avez choisi la solution de la facilité juste pour pas corriger ce bug, y'avait un beau challenge quand même ! :smirk:

**Comment by thomaslhostis** [comment]
Avec plaisir 😄 

Juste par curiosité, tu l'utilisais encore le mode bloc toi ?
