### ISSUE TITLE
Missing warning while overriding platform

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#53]
When a user create a platform_X from another platform_Y, if the platform_X already exist, it will be override by the valuation of platform_Y without noticing .

This behaviour is not an error but a heads up would be nice to ensure that this is really whats the user wants.

**Comment by thomaslhostis** [comment]
Fonctionnalité implémentée : l'utilisateur est averti et on lui demande de valider l'écrasement.
