### ISSUE TITLE
full mustache appliant

### ISSUE THREAD

**Issue by nboury-vsct** [voyages-sncf-technologies/hesperides-gui#54]
it shoud be great that hesperides applies mustache notations as described here https://mustache.github.io/mustache.5.html such as :
- last item 
- condition
- non false value ({{#person?}})

**Comment by Lucas-C** [comment]
cf. https://github.com/voyages-sncf-technologies/hesperides/issues/375

**Comment by thomaslhostis** [comment]
Demande à implémenter côté back => Ref https://github.com/voyages-sncf-technologies/hesperides/issues/375
