### ISSUE TITLE
Diff at module level

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#73]
When running diff against a module which have a property key referenced at the global level.

You will be able to preview your changes as expected, and you will be able to save whitout any error.

But given the behaviour of these kind of properties it will take automatically the value of the global properties instead of the one you just saved, leaving you with the feeling of a bug in Hesperides.

If you wish to save this value, go into the global properties diff.

To prevent loosing time and mind in this matter, it would be interesting to give the user a feedback saying that these are global and thus can't be save at a module level

**Comment by thomaslhostis** [comment]
@JordanKergoat J'ai l'impression que cette fonctionnalité a été implémentée. Peux-tu nous le confirmer ?

![2018-10-30 10_35_59-hesperides](https://user-images.githubusercontent.com/4296630/47709104-d7fc2600-dc2f-11e8-84d3-3416330f5c2a.png)

**Comment by Lucas-C** [comment]
Jordan m'a réexpliqué ça.

Voici un cas concret :
![2018-11-02 14_36_22-hesperides](https://user-images.githubusercontent.com/925560/47918411-d0958080-deac-11e8-8ed0-efd885f9f22d.png)

- dans le diff, on voit que la valeur de la propriété `global_property_foo` diffère
- hors cette propriété est une propriété **globale**
- donc effectuer une correction au niveau du module (`path: #ROOT_GROUP#PARENT_GROUP#CHILD_GROUP#module-tlh#1#WORKINGCOPY`) n'aura aucun effet

**Comment by Lucas-C** [comment]
Sera corrigé par https://github.com/voyages-sncf-technologies/hesperides-gui/pull/272
