### ISSUE TITLE
Diff ihm display issue with globals

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#74]
When the value of a property is too long and this property is automatically taken from global, the exclamtion sign is not displayed. Leading to miss understanding behaviour while trying to save them

#73

**Comment by thomaslhostis** [comment]
Suggestion : le div qui contient le texte et le warning a la propriété text-overflow: ellipsis. Il faudrait que cette propriété ne s'applique que sur le texte mais pas sur le warning.

![2018-10-30 11_12_17-hesperides](https://user-images.githubusercontent.com/4296630/47711118-b9e4f480-dc34-11e8-84b1-9ffeac749cf0.png)

**Comment by Lucas-C** [comment]
Corrigé par https://github.com/voyages-sncf-technologies/hesperides-gui/pull/272
