### ISSUE TITLE
Valuation field duplication if the template has the same key several times with and without comment

### ISSUE THREAD

**Issue by jceloi** [voyages-sncf-technologies/hesperides-gui#75]
Such an entry in a file template :
 `      "status": "{{train.api.uri|URI complète (protocole url port) de l'API train ou de son mock}}/status",
      "grant": "{{train.api.uri}}/grant",`

Generates two "train.api.uri" fields in the valuation form of that module.

Once one of those has a saved value, the other disappears.
The file is correctly generated.

**Comment by JordanKergoat** [comment]
We are currently aware of this situation, but we didn't find yet a reasonable solution to this matter.

The problem being the backward compatibility. And the divergent opinion about the right way to treat that case. 

Several case has come to us, but none of them has been choosen yet : 
- Add a declaration statement of the property with all annotation, and then later in template used without any anotation.
- Consider merging all annotations with the same property key name
- Taking the first the longest mustache statement of the multiple occurence as the "detailed one"

Each of these solutions has pros and cons, do not hesitate to give your personnal opinion about the way you would like to use them in template.

**Comment by Lucas-C** [comment]
Bug reporté côté backend : https://github.com/voyages-sncf-technologies/hesperides/issues/77
