### ISSUE TITLE
Display patterns in placeholder in iterable properties

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides-gui#77]
Just like simple properties, it will be usefull to display the pattern in placeholder to let the user know the pattern behind the property in template.

**Comment by stidiovip** [comment]
Fixed on [PR-85](https://github.com/voyages-sncf-technologies/hesperides-gui/pull/85)

**Comment by mareths** [comment]
Fixed on CHAOS_2.2.2
