### ISSUE TITLE
Global properties cache not up to date

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#84]
When saving properties using United Nation popup, the global properties cache is not invalidated, which cause global properties usage to be out of date.

Work Arround : Refresh the web page

**Comment by thomaslhostis** [comment]
@JordanKergoat Qu'est-ce que United Nation popup ?

**Comment by Lucas-C** [comment]
La "United nations popup" correspond à la fenêtre de "résolution des modifications locales de propriétés".

On y accède via ce bouton :
![2018-11-02 13_53_58-hesperides _ properties](https://user-images.githubusercontent.com/925560/47916592-f15ad780-dea6-11e8-9b95-fddb1d01bb70.png)

J'ai trouvé ce commentaire explicatif dans le code:

`// Why United Nations ? They are solving conflicts, rights ? :D`

**Comment by Lucas-C** [comment]
@JordanKergoat : penses-tu que ce bug existe toujours ?

**Comment by Lucas-C** [comment]
En lien avec https://github.com/voyages-sncf-technologies/hesperides-gui/issues/321
