### ISSUE TITLE
Global properties display issue when switching platforms

### ISSUE THREAD

**Issue by JordanKergoat** [voyages-sncf-technologies/hesperides-gui#88]
When you displayed global properties of any platform, and your switch from there to another platform, you will see that the global properties block is present but empty. No valuations appears, but if you click twice one the global properties display button you will see them appear.

This is a simple issue due of a miss reloaded data. You actually don't loose any of this properties

**Comment by thomaslhostis** [comment]
@JordanKergoat Nous n'avons pas réussi à reproduire le bug. D'après toi, est-ce que ça a été corrigé ?

**Comment by Lucas-C** [comment]
Vu avec Jordan : il l'a déjà corrigé ! 👏 🙌
