### ISSUE TITLE
Adding direct access to techno page from the module page

### ISSUE THREAD

**Issue by stidiovip** [voyages-sncf-technologies/hesperides-gui#90]
Up now, we have a link of techno page on module. But when we click on it, nothing hapens.
It'll be useful to open the techno when the link is clicked from module page.

**Comment by stidiovip** [comment]
Thank you @zessirb. I added the issue to the current developpement iteration.

**Comment by zessirb** [comment]
Link added with pull request #99

**Comment by JordanKergoat** [comment]
Actually, when you click on a techno on a module page, a new tab is open but the url is not corret.

Example : 
/#/techno/test-techno/1.0type=workingcopy
instead of 
/#/techno/test-techno/1.0?type=workingcopy

I guess there is just a question mark missing

**Comment by thomaslhostis** [comment]
Fixed
