### ISSUE TITLE
Add console error check in protractor

### ISSUE THREAD

**Issue by mareths** [voyages-sncf-technologies/hesperides-gui#98]
Add in all protractor tests a check of error display in console.

**Comment by thomaslhostis** [comment]
@mareths Hello, peux-tu préciser ta demande stp ? :)

**Comment by mareths** [comment]
Yop,

Me souvient plus trop de ça :sweat_smile:

Ça ressemble à rajouter des cas d'erreurs dans tout les tests protractor, genre jusqu'à maintenant, on n'a que des tests qui vérifie si tel ou tel élément est présent, mais pas de vérification en cas d'erreur.

**Comment by Lucas-C** [comment]
OK, je vois !

**Comment by Lucas-C** [comment]
Je clôture au profit de https://github.com/voyages-sncf-technologies/hesperides-gui/issues/279
